# Generated by Django 5.2.8 on 2025-12-26 22:53

import uuid

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
import recipes.models.followers
from django.conf import settings
from django.db import migrations, models

FOLLOW_REQUEST_STATUSES = [
    ('pending', 'Pending'),
    ('accepted', 'Accepted'),
    ('rejected', 'Rejected'),
]

NOTIFICATION_TYPES = [
    ('like', 'Like'),
    ('comment', 'Comment'),
    ('follow', 'Follow'),
    ('follow_request', 'Follow Request'),
    ('tag', 'Tag'),
]

RECIPE_VISIBILITY_CHOICES = [
    ('public', 'Public'),
    ('followers', 'Followers only'),
    ('close_friends', 'Close friends only'),
]

REPORT_REASONS = [
    ('spam', 'Spam'),
    ('inappropriate', 'Inappropriate Content'),
    ('harassment', 'Harassment'),
    ('other', 'Other'),
]

class Migration(migrations.Migration):

    replaces = [('recipes', '0001_initial'), ('recipes', '0002_recipepost_ingredient'), ('recipes', '0003_recipestep'), ('recipes', '0004_like'), ('recipes', '0005_comment'), ('recipes', '0006_favourite'), ('recipes', '0007_follows'), ('recipes', '0008_follower_remove_follows_uniq_follow_author_followee_and_more'), ('recipes', '0002_recipe'), ('recipes', '0009_merge_20251203_1708'), ('recipes', '0010_delete_recipe'), ('recipes', '0009_comment_is_hidden_recipepost_is_hidden_report'), ('recipes', '0011_merge_20251206_2021'), ('recipes', '0011_merge_20251206_1452'), ('recipes', '0012_merge_20251206_2112'), ('recipes', '0011_recipepost_category'), ('recipes', '0013_merge_20251209_2112'), ('recipes', '0014_ingredient_shop_url_alter_user_username'), ('recipes', '0015_remove_ingredient_shop_url'), ('recipes', '0016_ingredient_shop_url'), ('recipes', '0015_alter_user_username'), ('recipes', '0011_merge_20251206_2040'), ('recipes', '0012_merge_20251206_2100'), ('recipes', '0013_merge_20251207_2334'), ('recipes', '0014_merge_20251209_1218'), ('recipes', '0017_merge_20251210_1658'), ('recipes', '0018_notification'), ('recipes', '0015_merge_20251211_1050'), ('recipes', '0019_merge_0015_merge_20251211_1050_0018_notification'), ('recipes', '0019_merge_0014_merge_20251209_1218_0018_notification'), ('recipes', '0020_merge_20251211_1113'), ('recipes', '0021_ingredient_shop_image_url'), ('recipes', '0022_alter_ingredient_shop_image_url'), ('recipes', '0023_remove_ingredient_ingredient_position_gt_0_and_more'), ('recipes', '0020_user_avatar'), ('recipes', '0024_merge_20251212_0209'), ('recipes', '0021_recipeimage'), ('recipes', '0025_merge_0021_recipeimage_0024_merge_20251212_0209'), ('recipes', '0026_alter_ingredient_unique_together_and_more'), ('recipes', '0022_favouriteitem_remove_recipeimage_recipe_post_and_more'), ('recipes', '0002_user_bio'), ('recipes', '0023_merge_20251212_2018'), ('recipes', '0027_merge_20251212_2224'), ('recipes', '0028_recipeimage'), ('recipes', '0023_merge_20251212_2005'), ('recipes', '0029_merge_0023_merge_20251212_2005_0028_recipeimage'), ('recipes', '0024_user_is_private'), ('recipes', '0025_followrequest'), ('recipes', '0026_notification_follow_request'), ('recipes', '0027_closefriend'), ('recipes', '0028_recipepost_visibility'), ('recipes', '0030_merge_20251213_0426'), ('recipes', '0029_favourite_cover_post'), ('recipes', '0027_merge_20251212_2235'), ('recipes', '0031_merge_20251213_2356'), ('recipes', '0032_alter_ingredient_position'), ('recipes', '0033_merge_20251216_0059'), ('recipes', '0031_merge_20251214_1356'), ('recipes', '0034_merge_20251216_2348'), ('recipes', '0035_alter_user_bio_alter_user_username'), ('recipes', '0036_merge_20251219_2340'), ('recipes', '0037_recipepost_serves'), ('recipes', '0038_drop_follows')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must consist of at least three alphanumericals', regex='^\\w{3,}$')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, help_text='short user bio shown on profile', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_private', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RecipePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=4000)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('prep_time_min', models.PositiveIntegerField(default=0)),
                ('cook_time_min', models.PositiveIntegerField(default=0)),
                ('serves', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('nutrition', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=RECIPE_VISIBILITY_CHOICES, default='public', max_length=20)),
                ('saved_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by admin due to reports')),
                ('author', models.ForeignKey(db_column='author_id', on_delete=models.CASCADE, related_name='recipe_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipe_post',
            },
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_post', models.ForeignKey(on_delete=models.CASCADE, related_name='images', to='recipes.recipepost')),
            ],
            options={
                'ordering': ['position', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=1)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_url', models.URLField(blank=True, help_text='Link to buy this product online', max_length=500, null=True)),
                ('shop_image_upload', models.ImageField(blank=True, help_text='Custom image for this product in the Shop section', null=True, upload_to='shop_items/')),
                ('recipe_post', models.ForeignKey(db_column='recipe_post_id', on_delete=models.CASCADE, related_name='ingredients', to='recipes.recipepost')),
            ],
            options={
                'constraints': [models.CheckConstraint(check=models.Q(position__gt=0), name='ingredient_position_gt_0')],
                'unique_together': {('recipe_post', 'name'), ('recipe_post', 'position')},
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('recipe_post', models.ForeignKey(db_column='recipe_post_id', on_delete=models.CASCADE, related_name='steps', to='recipes.recipepost')),
            ],
            options={
                'db_table': 'recipe_step',
                'constraints': [models.CheckConstraint(check=models.Q(position__gt=0), name='recipe_step_position_gt_0')],
                'unique_together': {('recipe_post', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_post', models.ForeignKey(db_column='recipe_post_id', on_delete=models.CASCADE, related_name='likes', to='recipes.recipepost')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=models.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'like',
                'unique_together': {('user', 'recipe_post')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by admin due to reports')),
                ('recipe_post', models.ForeignKey(db_column='recipe_post_id', on_delete=models.CASCADE, related_name='comments', to='recipes.recipepost')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=models.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=REPORT_REASONS, max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details from the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Has an admin dealt with this?')),
                ('resolution_note', models.TextField(blank=True, help_text="Admin's notes on the decision")),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='reports', to='recipes.comment')),
                ('recipe_post', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='reports', to='recipes.recipepost')),
                ('reporter', models.ForeignKey(on_delete=models.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_post', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='cover_for_favourites', to='recipes.recipepost')),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourite',
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='uniq_favourite_user_name')],
                'indexes': [models.Index(fields=['user'], name='favourite_user_id_bf5a99_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavouriteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('favourite', models.ForeignKey(db_column='favourite_id', on_delete=models.CASCADE, related_name='items', to='recipes.favourite')),
                ('recipe_post', models.ForeignKey(db_column='recipe_post_id', on_delete=models.CASCADE, related_name='favourite_items', to='recipes.recipepost')),
            ],
            options={
                'db_table': 'favourite_item',
                'constraints': [models.UniqueConstraint(fields=('favourite', 'recipe_post'), name='uniq_favourite_item')],
                'indexes': [models.Index(fields=['favourite'], name='favourite_i_favouri_432d96_idx'), models.Index(fields=['recipe_post'], name='favourite_i_recipe__07ad1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.UUIDField(default=recipes.models.followers._uuid7_or_4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=models.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(db_column='follower_id', on_delete=models.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'followers',
                'constraints': [models.UniqueConstraint(fields=('follower', 'author'), name='uniq_followers_follower_author'), models.CheckConstraint(check=~models.Q(follower=models.F('author')), name='chk_followers_not_self')],
                'indexes': [models.Index(fields=['follower'], name='followers_followe_36be73_idx'), models.Index(fields=['author'], name='followers_author__5c6749_idx')],
            },
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=FOLLOW_REQUEST_STATUSES, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=models.CASCADE, related_name='follow_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=models.CASCADE, related_name='follow_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follow_request',
                'constraints': [models.UniqueConstraint(fields=('requester', 'target'), name='uniq_follow_request_requester_target'), models.CheckConstraint(check=~models.Q(requester=models.F('target')), name='chk_follow_request_not_self')],
            },
        ),
        migrations.CreateModel(
            name='CloseFriend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=models.CASCADE, related_name='close_friend_friend', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=models.CASCADE, related_name='close_friend_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'close_friend',
                'constraints': [models.UniqueConstraint(fields=('owner', 'friend'), name='uniq_close_friend_owner_friend'), models.CheckConstraint(check=~models.Q(owner=models.F('friend')), name='chk_close_friend_not_self')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=NOTIFICATION_TYPES, max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='recipes.comment')),
                ('follow_request', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='notifications', to='recipes.followrequest')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='recipes.recipepost')),
                ('recipient', models.ForeignKey(on_delete=models.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=models.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
