# Generated by Django 5.2.8 on 2025-11-28 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=4000)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('prep_time_min', models.PositiveIntegerField(default=0)),
                ('cook_time_min', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('nutrition', models.TextField(blank=True, null=True)),
                ('saved_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipe_post',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('recipe_post', models.ForeignKey(db_column='recipe_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipepost')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='ingredient_position_gt_0')],
                'unique_together': {('recipe_post', 'name'), ('recipe_post', 'position')},
            },
        ),
    ]
