# Generated by Django 5.2.8 on 2025-11-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipepost_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('recipe_post', models.ForeignKey(db_column='recipe_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipepost')),
            ],
            options={
                'db_table': 'recipe_step',
                'constraints': [models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='recipe_step_position_gt_0')],
                'unique_together': {('recipe_post', 'position')},
            },
        ),
    ]
