# Generated by Django 5.2.8 on 2025-11-28 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_post', models.ForeignKey(db_column='recipe_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='recipes.recipepost')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'like',
                'unique_together': {('user', 'recipe_post')},
            },
        ),
    ]
