# Generated by Django 5.2.8 on 2025-12-01 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('recipe_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='recipes.recipepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourite',
                'indexes': [models.Index(fields=['user'], name='favourite_user_id_bf5a99_idx'), models.Index(fields=['recipe_post'], name='favourite_recipe__6c5dc9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'recipe_post'), name='uniq_favourite_user_recipe_post')],
            },
        ),
    ]
