# Generated by Django 5.2.8 on 2025-12-01 16:46

import django.db.models.deletion
import recipes.models.follows
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.UUIDField(default=recipes.models.follows._uuid7_or_4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(db_column='follower_id', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('followee', models.ForeignKey(db_column='followee_id', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follow',
                'indexes': [models.Index(fields=['author'], name='follow_followe_1b4118_idx'), models.Index(fields=['followee'], name='follow_followe_af65f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('author', 'followee'), name='uniq_follow_author_followee'), models.CheckConstraint(condition=models.Q(('author', models.F('followee')), _negated=True), name='chk_follow_not_self')],
            },
        ),
    ]
