# Generated by Django 5.2.8 on 2025-12-01 17:01

import django.db.models.deletion
import recipes.models.followers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.UUIDField(default=recipes.models.followers._uuid7_or_4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'followers',
            },
        ),
        migrations.RemoveConstraint(
            model_name='follows',
            name='uniq_follow_author_followee',
        ),
        migrations.RemoveConstraint(
            model_name='follows',
            name='chk_follow_not_self',
        ),
        migrations.RenameIndex(
            model_name='follows',
            new_name='follows_author__32d43c_idx',
            old_name='follow_followe_1b4118_idx',
        ),
        migrations.RenameIndex(
            model_name='follows',
            new_name='follows_followe_b47de1_idx',
            old_name='follow_followe_af65f5_idx',
        ),
        migrations.AlterField(
            model_name='follows',
            name='author',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follows',
            name='followee',
            field=models.ForeignKey(db_column='followee_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='follows',
            constraint=models.UniqueConstraint(fields=('author', 'followee'), name='uniq_follows_author_followee'),
        ),
        migrations.AddConstraint(
            model_name='follows',
            constraint=models.CheckConstraint(condition=models.Q(('author', models.F('followee')), _negated=True), name='chk_follows_not_self'),
        ),
        migrations.AlterModelTable(
            name='follows',
            table='follows',
        ),
        migrations.AddField(
            model_name='follower',
            name='author',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(db_column='follower_id', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='follower',
            index=models.Index(fields=['follower'], name='followers_followe_36be73_idx'),
        ),
        migrations.AddIndex(
            model_name='follower',
            index=models.Index(fields=['author'], name='followers_author__5c6749_idx'),
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('follower', 'author'), name='uniq_followers_follower_author'),
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('author')), _negated=True), name='chk_followers_not_self'),
        ),
    ]
