# Generated by Django 5.2.8 on 2025-12-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe'),
        ('recipes', '0008_follower_remove_follows_uniq_follow_author_followee_and_more'),
    ]

    operations = [
    ]
