# Generated by Django 5.2.8 on 2025-12-04 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_follower_remove_follows_uniq_follow_author_followee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden by admin due to reports'),
        ),
        migrations.AddField(
            model_name='recipepost',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden by admin due to reports'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details from the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Has an admin dealt with this?')),
                ('resolution_note', models.TextField(blank=True, help_text="Admin's notes on the decision")),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='recipes.comment')),
                ('recipe_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='recipes.recipepost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-created_at'],
            },
        ),
    ]
