# Generated by Django 5.2.8 on 2025-12-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_merge_20251203_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
