# Generated by Django 5.2.8 on 2025-12-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_comment_is_hidden_recipepost_is_hidden_report'),
        ('recipes', '0010_delete_recipe'),
    ]

    operations = [
    ]
