# Generated by Django 5.2.8 on 2025-12-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_delete_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepost',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
