# Generated by Django 5.2.8 on 2025-12-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_merge_20251206_1452'),
        ('recipes', '0011_merge_20251206_2040'),
    ]

    operations = [
    ]
