# Generated by Django 5.2.8 on 2025-12-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipepost_category'),
        ('recipes', '0012_merge_20251206_2112'),
    ]

    operations = [
    ]
