# Generated by Django 5.2.8 on 2025-12-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_merge_20251206_2100'),
        ('recipes', '0012_merge_20251206_2112'),
    ]

    operations = [
    ]
