# Generated by Django 5.2.8 on 2025-12-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipepost_category'),
        ('recipes', '0013_merge_20251207_2334'),
    ]

    operations = [
    ]
