# Generated by Django 5.2.8 on 2025-12-09 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_merge_20251209_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='shop_url',
            field=models.URLField(blank=True, help_text='Link to buy this product online', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must consist of @ followed by at least three alphanumericals', regex='^\\w{3,}$')]),
        ),
    ]
