# Generated by Django 5.2.8 on 2025-12-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_ingredient_shop_url_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='shop_url',
        ),
    ]
