# Generated by Django 5.2.8 on 2025-12-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_ingredient_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='shop_url',
            field=models.URLField(blank=True, help_text='Link to buy this product online', max_length=500, null=True),
        ),
    ]
