# Generated by Django 5.2.8 on 2025-12-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_merge_20251209_1218'),
        ('recipes', '0015_alter_user_username'),
        ('recipes', '0016_ingredient_shop_url'),
    ]

    operations = [
    ]
