# Generated by Django 5.2.8 on 2025-12-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_merge_20251211_1050'),
        ('recipes', '0018_notification'),
    ]

    operations = [
    ]
