# Generated by Django 5.2.8 on 2025-12-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_merge_20251209_1218'),
        ('recipes', '0018_notification'),
    ]

    operations = [
    ]
