# Generated by Django 5.2.8 on 2025-12-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_merge_20251211_1011'),
        ('recipes', '0019_merge_0015_merge_20251211_1050_0018_notification'),
    ]

    operations = [
    ]
