# Generated by Django 5.2.8 on 2025-01-05
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0019_merge_0015_merge_20251211_1050_0018_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]