# Generated by Django 5.2.8 on 2025-01-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0020_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="recipes/")),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe_post",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="recipes.recipepost"),
                ),
            ],
            options={"ordering": ["position", "created_at", "id"]},
        ),
    ]

