# Generated by Django 5.2.8 on 2025-12-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_merge_20251211_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='shop_image_url',
            field=models.URLField(blank=True, help_text='Automatically scraped product image', max_length=800, null=True),
        ),
    ]
