# Generated by Django 5.2.8 on 2025-12-12 19:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_recipeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favourite_item',
            },
        ),
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe_post',
        ),
        migrations.RemoveConstraint(
            model_name='favourite',
            name='uniq_favourite_user_recipe_post',
        ),
        migrations.RemoveIndex(
            model_name='favourite',
            name='favourite_recipe__6c5dc9_idx',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='recipe_post',
        ),
        migrations.AddField(
            model_name='favourite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourite',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favourite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_favourite_user_name'),
        ),
        migrations.AddField(
            model_name='favouriteitem',
            name='favourite',
            field=models.ForeignKey(db_column='favourite_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.favourite'),
        ),
        migrations.AddField(
            model_name='favouriteitem',
            name='recipe_post',
            field=models.ForeignKey(db_column='recipe_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='favourite_items', to='recipes.recipepost'),
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
        migrations.AddIndex(
            model_name='favouriteitem',
            index=models.Index(fields=['favourite'], name='favourite_i_favouri_432d96_idx'),
        ),
        migrations.AddIndex(
            model_name='favouriteitem',
            index=models.Index(fields=['recipe_post'], name='favourite_i_recipe__07ad1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='favouriteitem',
            constraint=models.UniqueConstraint(fields=('favourite', 'recipe_post'), name='uniq_favourite_item'),
        ),
    ]
