# Generated by Django 5.2.8 on 2025-12-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_merge_20251211_1132'),
        ('recipes', '0021_auto_20251211_1138'),
    ]

    operations = [
    ]
