# Generated by Django 5.2.8 on 2025-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_ingredient_shop_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='shop_image_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
