# Generated by Django 5.2.8 on 2025-12-12 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_merge_20251211_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.favourite')),
                ('recipe_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_items', to='recipes.recipepost')),
            ],
            options={
                'db_table': 'favourite_item',
                'indexes': [models.Index(fields=['favourite'], name='favourite_i_favouri_432d96_idx'), models.Index(fields=['recipe_post'], name='favourite_i_recipe__07ad1d_idx')],
                'constraints': [models.UniqueConstraint(fields=('favourite', 'recipe_post'), name='uniq_favourite_item')],
            },
        ),
    ]
