# Generated by Django 5.2.8 on 2025-12-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_alter_ingredient_shop_image_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_position_gt_0',
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
    ]
