# Generated by Django 5.2.8 on 2025-12-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_user_bio'),
        ('recipes', '0022_favouriteitem_remove_recipeimage_recipe_post_and_more'),
    ]

    operations = [
    ]
