# Generated by Django 5.2.8 on 2025-12-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_user_avatar'),
        ('recipes', '0023_remove_ingredient_ingredient_position_gt_0_and_more'),
    ]

    operations = [
    ]
