# Generated by Django 5.2.8 on 2025-12-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_recipeimage'),
        ('recipes', '0024_merge_20251212_0209'),
    ]

    operations = [
    ]
