# Generated by Django 5.2.8 on 2025-12-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_merge_0021_recipeimage_0024_merge_20251212_0209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('recipe_post', 'name'), ('recipe_post', 'position')},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='shop_image_upload',
            field=models.ImageField(blank=True, help_text='Custom image for this product in the Shop section', null=True, upload_to='shop_items/'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='ingredient_position_gt_0'),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='shop_image_url',
        ),
    ]
