# Generated by Django 5.2.8 on 2025-01-08
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0026_notification_follow_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloseFriend",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("friend", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="close_friend_friend", to=settings.AUTH_USER_MODEL)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="close_friend_owner", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "close_friend",
            },
        ),
        migrations.AddConstraint(
            model_name="closefriend",
            constraint=models.UniqueConstraint(fields=("owner", "friend"), name="uniq_close_friend_owner_friend"),
        ),
        migrations.AddConstraint(
            model_name="closefriend",
            constraint=models.CheckConstraint(check=models.Q(("owner", models.F("friend")), _negated=True), name="chk_close_friend_not_self"),
        ),
    ]
