# Generated by Django 5.2.8 on 2025-12-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_merge_20251212_2018'),
        ('recipes', '0026_alter_ingredient_unique_together_and_more'),
    ]

    operations = [
    ]
