# Generated by Django 5.2.8 on 2025-01-08
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0027_closefriend"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipepost",
            name="visibility",
            field=models.CharField(choices=[("public", "Public"), ("followers", "Followers only"), ("close_friends", "Close friends only")], default="public", max_length=20),
        ),
    ]
