# Generated by Django 5.2.8 on 2025-12-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_merge_20251212_2005'),
        ('recipes', '0028_recipeimage'),
    ]

    operations = [
    ]
