# Generated by Django 5.2.8 on 2025-12-13 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='cover_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_favourites', to='recipes.recipepost'),
        ),
    ]
