# Generated by Django 5.2.8 on 2025-12-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_recipepost_visibility'),
        ('recipes', '0029_merge_0023_merge_20251212_2005_0028_recipeimage'),
    ]

    operations = [
    ]
