# Generated by Django 5.2.8 on 2025-12-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_merge_20251212_2235'),
        ('recipes', '0029_favourite_cover_post'),
        ('recipes', '0030_merge_20251213_0426'),
    ]

    operations = [
    ]
