# Generated by Django 5.2.8 on 2025-12-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_merge_20251213_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
