# Generated by Django 5.2.8 on 2025-12-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_merge_20251214_1356'),
        ('recipes', '0033_merge_20251216_0059'),
    ]

    operations = [
    ]
