# Generated by Django 5.2.8 on 2025-12-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0036_merge_20251219_2340"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipepost",
            name="serves",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
